import React, { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Check, FilePenLine, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import type { HomebrewModuleType } from "@shared/homebrewRules";

type ChildKind = "caracteristica" | "talento" | "evolucao" | "penalidade" | "propriedade";

const categoriesByModule: Partial<Record<HomebrewModuleType, Array<{ type: ChildKind; label: string; helper: string }>>> = {
  origem: [
    { type: "caracteristica", label: "Características", helper: "Traços e efeitos próprios da origem." },
    { type: "talento", label: "Talentos", helper: "Talentos com requisitos, bônus, efeitos e evolução." },
    { type: "penalidade", label: "Penalidades", helper: "Limitações com efeitos estruturados." },
    { type: "evolucao", label: "Evoluções", helper: "Progressões adquiridas a partir da origem." },
  ],
  armas: [
    { type: "caracteristica", label: "Características", helper: "Traços próprios e efeitos mecânicos da arma." },
    { type: "propriedade", label: "Propriedades", helper: "Características e propriedades mecânicas da arma." },
  ],
};

const requirementOptions = ["atributo", "nivel", "origem", "voto", "aptidao", "especializacao", "tecnica", "item", "condicao", "custom"] as const;

export function StructuredElementChildren({ homebrewId, moduleId, moduleType, parentElementId, allowedKinds, sectionTitle, sectionDescription }: { homebrewId: number; moduleId: number; moduleType: HomebrewModuleType; parentElementId: number; allowedKinds?: ChildKind[]; sectionTitle?: string; sectionDescription?: string }) {
  const categories = (categoriesByModule[moduleType] ?? []).filter(category => !allowedKinds || allowedKinds.includes(category.type));
  const [kind, setKind] = useState<ChildKind>(categories[0]?.type ?? "caracteristica");
  const [ruleSource, setRuleSource] = useState<"official" | "homebrew" | "manual">("homebrew");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editingName, setEditingName] = useState("");
  const [editingDescription, setEditingDescription] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [requirementType, setRequirementType] = useState<(typeof requirementOptions)[number]>("atributo");
  const [requirementValue, setRequirementValue] = useState("");
  const [bonusAttribute, setBonusAttribute] = useState("");
  const [bonusValue, setBonusValue] = useState("1");
  const [effectDescription, setEffectDescription] = useState("");

  const childrenQuery = trpc.homebrew.structuredList.useQuery({ homebrewId, moduleId, parentElementId });
  const activeChild = useMemo(() => childrenQuery.data?.find(item => item.id === selectedId) ?? childrenQuery.data?.[0], [childrenQuery.data, selectedId]);
  const mechanicsQuery = trpc.homebrew.structuredMechanics.useQuery({ homebrewId, elementId: activeChild?.id ?? 0 }, { enabled: Boolean(activeChild?.id) });
  const evolutionUnlocksQuery = trpc.homebrew.structuredEvolutionUnlocks.useQuery({ homebrewId, evolutionElementId: activeChild?.id ?? 0 }, { enabled: activeChild?.type === "evolucao" });
  const createMutation = trpc.homebrew.structuredCreate.useMutation({ onSuccess: () => { setName(""); setDescription(""); setRuleSource("homebrew"); childrenQuery.refetch(); toast.success("Item vinculado criado."); }, onError: error => toast.error(error.message) });
  const updateMutation = trpc.homebrew.structuredUpdate.useMutation({ onSuccess: () => { setEditingId(null); childrenQuery.refetch(); toast.success("Item vinculado atualizado."); }, onError: error => toast.error(error.message) });
  const deleteMutation = trpc.homebrew.structuredDelete.useMutation({ onSuccess: () => { setSelectedId(null); childrenQuery.refetch(); toast.success("Item vinculado removido."); }, onError: error => toast.error(error.message) });
  const reorderMutation = trpc.homebrew.structuredReorder.useMutation({ onSuccess: () => childrenQuery.refetch(), onError: error => toast.error(error.message) });
  const saveMechanicsMutation = trpc.homebrew.structuredSaveMechanics.useMutation({ onSuccess: () => { setRequirementValue(""); setBonusAttribute(""); setEffectDescription(""); mechanicsQuery.refetch(); toast.success("Mecânicas do item salvas."); }, onError: error => toast.error(error.message) });
  const replaceEvolutionUnlocksMutation = trpc.homebrew.structuredEvolutionUnlocksReplace.useMutation({ onSuccess: () => { evolutionUnlocksQuery.refetch(); toast.success("Itens liberados pela Evolução atualizados."); }, onError: error => toast.error(error.message) });

  if (categories.length === 0) return null;
  const items = (childrenQuery.data ?? []).filter(item => categories.some(category => category.type === item.type));
  const mechanics = mechanicsQuery.data;
  const selectedCategory = categories.find(category => category.type === kind) ?? categories[0];

  return (
    <section className="mt-3 rounded-xl border border-fuchsia-300/10 bg-fuchsia-500/[0.025] p-4">
      <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-fuchsia-200">{sectionTitle ?? "Estrutura vinculada"}</p><p className="mt-1 text-[11px] leading-relaxed text-stone-500">{sectionDescription ?? "Registros filhos mantêm posição, referência ao elemento pai, origem da regra e suas próprias mecânicas."}</p></div><span className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-stone-400">{items.length} itens</span></div>
      <div className="mt-3 grid gap-2 md:grid-cols-[150px_120px_1fr_1fr_auto]"><select aria-label="Categoria de item vinculado" value={kind} onChange={event => setKind(event.target.value as ChildKind)} className="h-9 rounded-md border border-white/8 bg-[#201b29] px-2 text-xs text-stone-300">{categories.map(category => <option key={category.type} value={category.type}>{category.label}</option>)}</select><select aria-label="Fonte da regra do item vinculado" value={ruleSource} onChange={event => setRuleSource(event.target.value as "official" | "homebrew" | "manual")} className="h-9 rounded-md border border-white/8 bg-[#201b29] px-2 text-xs text-stone-300"><option value="homebrew">Homebrew</option><option value="official">Oficial</option><option value="manual">Manual</option></select><Input value={name} onChange={event => setName(event.target.value)} placeholder={`Nome da ${selectedCategory.label.toLowerCase().slice(0, -1)}`} className="h-9 bg-black/15 text-xs" /><Input value={description} onChange={event => setDescription(event.target.value)} placeholder={selectedCategory.helper} className="h-9 bg-black/15 text-xs" /><Button size="sm" disabled={!name.trim() || !description.trim() || createMutation.isPending} onClick={() => createMutation.mutate({ homebrewId, moduleId, parentElementId, type: kind, name: name.trim(), description: description.trim(), ruleSource, isManual: ruleSource === "manual" })} className="h-9 bg-fuchsia-600 text-xs hover:bg-fuchsia-500"><Plus size={13} /> Adicionar</Button></div>
      <div className="mt-3 space-y-2">{items.map((item, index) => <div key={item.id} className={`rounded-lg border p-3 ${activeChild?.id === item.id ? "border-fuchsia-300/25 bg-fuchsia-500/[0.05]" : "border-white/7 bg-black/10"}`}>{editingId === item.id ? <div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input value={editingName} onChange={event => setEditingName(event.target.value)} className="h-8 bg-black/15 text-xs" /><Input value={editingDescription} onChange={event => setEditingDescription(event.target.value)} className="h-8 bg-black/15 text-xs" /><div className="flex gap-1"><Button size="sm" aria-label={`Salvar ${item.name}`} disabled={!editingName.trim() || !editingDescription.trim()} onClick={() => updateMutation.mutate({ homebrewId, id: item.id, name: editingName.trim(), description: editingDescription.trim() })}><Check size={13} /></Button><Button size="sm" variant="ghost" onClick={() => setEditingId(null)}>Cancelar</Button></div></div> : <div className="flex items-start justify-between gap-3"><button type="button" onClick={() => setSelectedId(item.id)} className="min-w-0 flex-1 text-left"><p className="text-xs font-semibold text-stone-200">{item.name}</p><p className="mt-1 text-[11px] text-stone-500">{item.description}</p></button><div className="flex items-center gap-1"><button type="button" aria-label={`Editar ${item.name}`} onClick={() => { setEditingId(item.id); setEditingName(item.name); setEditingDescription(item.description); }} className="rounded p-1 text-stone-500 hover:bg-white/8 hover:text-stone-200"><FilePenLine size={13} /></button><button type="button" aria-label={`Mover ${item.name} para cima`} disabled={index === 0} onClick={() => reorderMutation.mutate({ homebrewId, id: item.id, direction: "up" })} className="rounded p-1 text-stone-500 hover:bg-white/8 hover:text-stone-200 disabled:opacity-30"><ArrowUp size={13} /></button><button type="button" aria-label={`Mover ${item.name} para baixo`} disabled={index === items.length - 1} onClick={() => reorderMutation.mutate({ homebrewId, id: item.id, direction: "down" })} className="rounded p-1 text-stone-500 hover:bg-white/8 hover:text-stone-200 disabled:opacity-30"><ArrowDown size={13} /></button><button type="button" aria-label={`Excluir ${item.name}`} onClick={() => deleteMutation.mutate({ homebrewId, id: item.id })} className="rounded p-1 text-stone-500 hover:bg-rose-500/10 hover:text-rose-300"><Trash2 size={13} /></button></div></div>}</div>)}{!items.length && <p className="rounded-lg border border-dashed border-white/8 px-3 py-4 text-center text-[11px] text-stone-600">Adicione {selectedCategory.label.toLowerCase()} para vincular ao elemento selecionado.</p>}</div>
      {activeChild && <div className="mt-3 rounded-lg border border-white/7 bg-black/10 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-fuchsia-200">Mecânicas de {activeChild.name}</p><div className="mt-2 grid gap-2 md:grid-cols-4"><select aria-label="Tipo de requisito vinculado" value={requirementType} onChange={event => setRequirementType(event.target.value as (typeof requirementOptions)[number])} className="h-8 rounded-md border border-white/8 bg-[#201b29] px-2 text-xs text-stone-300">{requirementOptions.map(option => <option key={option} value={option}>{option}</option>)}</select><Input value={requirementValue} onChange={event => setRequirementValue(event.target.value)} placeholder="Valor do requisito" className="h-8 bg-black/15 text-xs" /><Input value={bonusAttribute} onChange={event => setBonusAttribute(event.target.value)} placeholder="Atributo do bônus" className="h-8 bg-black/15 text-xs" /><Input type="number" value={bonusValue} onChange={event => setBonusValue(event.target.value)} placeholder="Valor" className="h-8 bg-black/15 text-xs" /><Input value={effectDescription} onChange={event => setEffectDescription(event.target.value)} placeholder="Efeito ou penalidade" className="h-8 bg-black/15 text-xs md:col-span-4" /></div><div className="mt-2 flex items-center justify-between gap-3"><span className="text-[10px] text-stone-500">{mechanics ? `${mechanics.requirements.length} requisitos · ${mechanics.attributeBonuses.length} bônus · ${mechanics.effects.length} efeitos` : "Carregando mecânicas..."}</span><Button size="sm" disabled={!mechanics || (!requirementValue.trim() && !bonusAttribute.trim() && !effectDescription.trim()) || saveMechanicsMutation.isPending} onClick={() => saveMechanicsMutation.mutate({ homebrewId, elementId: activeChild.id, requirements: requirementValue.trim() ? [...mechanics!.requirements.map(item => ({ type: item.type, operator: item.operator, valueText: item.valueText, valueNumber: item.valueNumber })), { type: requirementType, valueText: requirementValue.trim() }] : mechanics!.requirements.map(item => ({ type: item.type, operator: item.operator, valueText: item.valueText, valueNumber: item.valueNumber })), attributeBonuses: bonusAttribute.trim() ? [...mechanics!.attributeBonuses.map(item => ({ attribute: item.attribute, value: item.value })), { attribute: bonusAttribute.trim(), value: Number(bonusValue) || 0 }] : mechanics!.attributeBonuses.map(item => ({ attribute: item.attribute, value: item.value })), effects: effectDescription.trim() ? [...mechanics!.effects.map(item => ({ effectType: item.effectType, description: item.description, valueNumber: item.valueNumber })), { effectType: "text", description: effectDescription.trim() }] : mechanics!.effects.map(item => ({ effectType: item.effectType, description: item.description, valueNumber: item.valueNumber })) })}>Salvar mecânicas</Button></div></div>}
      {activeChild?.type === "evolucao" && <div className="mt-3 rounded-lg border border-fuchsia-300/10 bg-fuchsia-500/[0.025] p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-fuchsia-200">Características e Talentos adicionados</p><p className="mt-1 text-[10px] leading-relaxed text-stone-500">Selecione os registros da mesma Origem que passam a ser liberados por esta Evolução.</p><div className="mt-2 flex flex-wrap gap-2">{(childrenQuery.data ?? []).filter(item => item.type === "caracteristica" || item.type === "talento").map(item => { const selected = (evolutionUnlocksQuery.data ?? []).some(unlock => unlock.unlockedElementId === item.id); return <button type="button" key={item.id} aria-pressed={selected} onClick={() => replaceEvolutionUnlocksMutation.mutate({ homebrewId, evolutionElementId: activeChild.id, unlockedElementIds: selected ? (evolutionUnlocksQuery.data ?? []).filter(unlock => unlock.unlockedElementId !== item.id).map(unlock => unlock.unlockedElementId) : [...(evolutionUnlocksQuery.data ?? []).map(unlock => unlock.unlockedElementId), item.id] })} className={`rounded-md border px-2 py-1 text-[10px] ${selected ? "border-fuchsia-300/35 bg-fuchsia-500/15 text-fuchsia-100" : "border-white/8 bg-black/10 text-stone-400 hover:text-stone-200"}`}>{item.type === "talento" ? "Talento" : "Característica"}: {item.name}</button>; })}</div></div>}
    </section>
  );
}
